### ISSUE TITLE
feature: Add symbol to indicate experimental and/or non-standard attrs/props

### ISSUE THREAD

**Issue by rschristian** [potahtml/namespace-jsx-project#2]
It'd be nice, if it's not too much of a pain, if there was an additional symbol for the attribute/property keys to indicate experimental and/or non-standard status.

For Preact at least, we generally prefer to only add properties once they've been properly standardized, else, we'd end up with some non-standard properties that have fallen out of use but we can't really remove without breaking someone's app. Users in their own apps could of course extend the types we set if they want to be early adopters.

Similar to 🛑, it would indicate why some frameworks might have it but not others (early adopters/supporters vs forgotten or missing).

Not sure if that'd be too much of a pain to maintain though, as some do move pretty quick.

**Comment by titoBouzout** [comment]
I've added three new indicators

- 🧪 indicates the key it's experimental (live from mdn)
- 🔥 indicates the key it's non-standard (live from mdn)
- 🤷‍♀️ indicates something weird is going on with key (to be investigated)

I am taking the data from MDN for this. The third indicator is because some of the keys I had previously marked as _deprecated_ cannot be found marked as such in MDN. This is most likely MDN lacking some information, as I somewhat quadruple-checked these keys in the past. I will need to see how to update MDN. Because now the information about _ley_ deprecation comes from MDN instead of being hardcoded. Unless it's a very old tagName that MDN no longer has a page for it.

Btw, can you speak with someone from Preact to fund this project or put me in contact with someone that can do so? That would be immensely appreciated, thanks

**Comment by rschristian** [comment]
Neat, thanks!

> Btw, can you speak with someone from Preact to fund this project or put me in contact with someone that can do so? That would be immensely appreciated, thanks

Can you clarify how much you're looking for?

Edit: Feel free to DM me on Twitter, BlueSky, or the Preact slack

**Comment by titoBouzout** [comment]
Thanks, will do

**Comment by titoBouzout** [comment]
@rschristian I can't DM you in BlueSky, anyway. I'm using open collective, what about matching Solid funding (1000) for three months or so? 
This is the link https://opencollective.com/tito-bouzout
Thanks for your support!

**Comment by rschristian** [comment]
Oh thanks, fixed the setting on BlueSky. Didn't realize that defaulted to a more restricted setting.

---

I'm sorry, I was expecting more in the range of $5/mo for a few months maybe. For what the project is, and the contributions to Preact, I don't think we'd go above that.

The reality is that none of us on the Preact team are paid to work part or full time on Preact, all of us contribute on our own time with only a handful of minor exceptions over the last few years. As such, our funding has gone to maintainers who've contributed tens, if not hundreds, of hours to the project directly and are active in feature development, triaging issues, fixing bugs, planning, maintenance, etc. This is a neat project that I've found useful to correct a few property types, but funding of that amount is going to require serious direct contributions to Preact, likely for many months. Some indirect type fixes just don't hit that level I'm afraid.

For reference (and this is all quite public), I began contributing to [`preact-cli`](https://github.com/preactjs/preact-cli) in May of 2020, was given a little bit of internal access in Sept 2020 after consistently triaging & helping users, and then given maintainer status in the org in early December of 2020, following our release of [`wmr`](https://github.com/preactjs/wmr) which I helped with. I've been a core maintainer since and hadn't received any funding for this until April of this year, since which I've received $3k.

I know this isn't what you wanted to hear, for which I apologize, and by all means, if you can only spend time updating Preact's info with the expectation of funding, absolutely skip it. Look after yourself first, OSS is if you have some time to donate back.

**Comment by rschristian** [comment]
Going to close this on out as the actual issue has been addressed, we can continue the other conversation here or elsewhere of course though.

**Comment by titoBouzout** [comment]
@rschristian Thanks, as you asked I thought it was more involved, but yeah I understand. Well anything is better than nothing, so as you consider should be good enough

**Comment by rschristian** [comment]
Sorry, I realize only now the amount I listed was a typo, supposed to be $15/mo. Still a far cry from the original dollar value of course, but a tad more I guess.

I did bring it up but apparently our OpenCollective has some restrictions of some sort that I'm not familiar with (I don't use the platform much myself) so that might take time. Will keep you updated, but that's the current status.

**Comment by titoBouzout** [comment]
No worries, much appreciate!
